export const Gender = {
  MALE: "male",
  FEMALE: "female",
  OTHER: "other",
};

export const Provider = {
  LOCAL: "local",
  GOOGLE: "google",
};

export const MedicineType = {
  PILLS: "Pills",
  CAPSULE: "Capsule",
  INJECTIONS: "Injections",
  LIQUID: "Liquid",
  TABLET: "Tablet",
  SYRUP: "Syrup",
  INHALER: "Inhaler",
  DROPS: "Drops",
  CREAM: "Cream",
  INHALATION: "Inhalation",
  OINTMENT: "Ointment",
  SOLUTION: "Solution",
  SYRINGE: "Syringe",
  TOPICAL: "Topical",
  VACCINE: "Vaccine",
  PATCH : "Patch",
  OTHERS: "Others",
};

export const Frequency = {
  DAILY: "Daily",
  WEEKLY: "Weekly",
  MONTHLY: "Monthly",
  AS_NEEDED: "As Needed",
};

export const DayOfWeek = {
  SAT: "Sat",
  SUN: "Sun",
  MON: "Mon",
  TUE: "Tue",
  WED: "Wed",
  THU: "Thu",
  FRI: "Fri",
};

export const IntakeInstruction = {
  AFTER_EAT: "After eat",
  WHILE_EATING: "While eating",
  BEFORE_EAT: "Before eat",
  AT_BEDTIME: "At Bedtime",
  EMPTY_STOMACH: "Empty stomach",
};

export const ReminderStatus = {
  PENDING: 'Pending',
  TAKEN: 'Taken',
  MISSED: 'Missed',
  SKIPPED: 'Skipped',
};

export const Images = {
  PATIENT_FEMALE: "default_patient_female",
  PATIENT_MALE : "default_patient_male",
  OTHER : "default_patient_other",
  DOCTOR_FEMALE : "default_doctor_female",
  DOCTOR_MALE:"default_doctor_male"
}

export const Diseases = [
  "Acne",
  "Acute Flaccid Myelitis (AFM)",
  "Addison’s Disease",
  "Adenovirus Infection",
  "AIDS",
  "Alzheimer’s Disease",
  "Anemia",
  "Ankylosing Spondylitis",
  "Anorexia Nervosa",
  "Anthrax",
  "Arthritis",
  "Asthma",
  "Atherosclerosis",
  "Autism Spectrum Disorder",
  "Bipolar Disorder",
  "Bladder Cancer",
  "Breast Cancer",
  "Bronchitis",
  "Bulimia Nervosa",
  "Cancer",
  "Celiac Disease",
  "Cervical Cancer",
  "Chickenpox",
  "Chlamydia",
  "Cholera",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Cirrhosis",
  "Colorectal Cancer",
  "Congestive Heart Failure",
  "Crohn’s Disease",
  "Cystic Fibrosis",
  "Dengue Fever",
  "Depression",
  "Diabetes",
  "Diverticulitis",
  "Down Syndrome",
  "Ebola Virus Disease",
  "Eczema",
  "Endometriosis",
  "Epilepsy",
  "Epidermolysis Bullosa",
  "Fibromyalgia",
  "Fifth Disease",
  "Food Allergies",
  "Gallstones",
  "Gastritis",
  "Gastroenteritis",
  "Genital Herpes",
  "Genital Warts",
  "Giardiasis",
  "Glaucoma",
  "Gonorrhea",
  "Gout",
  "Graves’ Disease",
  "Haemophilus Influenzae Invasive Disease",
  "Hand, Foot, and Mouth Disease",
  "Hantavirus",
  "Heart Disease",
  "Hemophilia",
  "Hepatitis A",
  "Hepatitis B",
  "Hepatitis C",
  "Herpes",
  "HIV",
  "Huntington’s Disease",
  "Hypertension",
  "Hypothyroidism",
  "Ichthyosis",
  "Influenza",
  "Irritable Bowel Syndrome (IBS)",
  "Juvenile Arthritis",
  "Kawasaki Disease",
  "Kidney Stones",
  "Legionellosis",
  "Leprosy",
  "Leptospirosis",
  "Leukemia",
  "Liver Cancer",
  "Lung Cancer",
  "Lupus",
  "Lyme Disease",
  "Malaria",
  "Marfan Syndrome",
  "Measles",
  "Meningitis",
  "Migraine",
  "Molluscum Contagiosum",
  "Mononucleosis",
  "Mpox",
  "Multiple Sclerosis",
  "Mumps",
  "Muscular Dystrophy",
  "Myasthenia Gravis",
  "Norovirus",
  "Obesity",
  "Obsessive-Compulsive Disorder (OCD)",
  "Osteogenesis Imperfecta",
  "Osteonecrosis",
  "Osteopetrosis",
  "Osteoporosis",
  "Ovarian Cancer",
  "Pancreatic Cancer",
  "Parkinson’s Disease",
  "Peptic Ulcer",
  "Pertussis",
  "Pneumonia",
  "Polio",
  "Post-Traumatic Stress Disorder (PTSD)",
  "Prostate Cancer",
  "Psoriasis",
  "Q Fever",
  "Rabies",
  "Rheumatoid Arthritis",
  "Rubella",
  "Salmonellosis",
  "Scabies",
  "Schizophrenia",
  "Sickle Cell Anemia",
  "Sinusitis",
  "Skin Cancer",
  "Stroke",
  "Syphilis",
  "Tetanus",
  "Thyroid Cancer",
  "Tonsillitis",
  "Tuberculosis",
  "Ulcerative Colitis",
  "Urinary Tract Infection (UTI)",
  "Varicella",
  "Whooping Cough",
  "Yellow Fever",
  "Zika Virus"
];

// Comment to encourage updates
// TODO: Update this list periodically with new diseases identified in 2025 from sources like WHO or CDC.

export const DiseaseType={
  CHRONIC: "chronic",
  NORMAL : "normal",
  GENETIC: "Genetic",
}

export const LifeStyleName = {
  SMOKER: "Smoker",
  EXERCISER: "Exerciser",
  ALCOHOL_USER: "Alcohol User",
  DIET_CHANGER: "Diet Changer",
  DRUG_USE:"drugUse"
};


export const Specialties = {
  ALLERGY_IMMUNOLOGY: "Allergy and Immunology",
  ANESTHESIOLOGY: "Anesthesiology",
  CARDIOLOGY: "Cardiology",
  CARDIOTHORACIC_SURGERY: "Cardiothoracic Surgery",
  COLORECTAL_SURGERY: "Colorectal Surgery",
  CRITICAL_CARE_MEDICINE: "Critical Care Medicine",
  DERMATOLOGY: "Dermatology",
  EMERGENCY_MEDICINE: "Emergency Medicine",
  ENDOCRINOLOGY: "Endocrinology",
  FAMILY_MEDICINE: "Family Medicine",
  FORENSIC_PATHOLOGY: "Forensic Pathology",
  GASTROENTEROLOGY: "Gastroenterology",
  GERIATRICS: "Geriatrics",
  GENERAL_SURGERY: "General Surgery",
  GYNECOLOGY: "Gynecology",
  HEMATOLOGY: "Hematology",
  INFECTIOUS_DISEASE: "Infectious Disease",
  INTERNAL_MEDICINE: "Internal Medicine",
  INTERVENTIONAL_CARDIOLOGY: "Interventional Cardiology",
  INTERVENTIONAL_RADIOLOGY: "Interventional Radiology",
  MEDICAL_GENETICS: "Medical Genetics",
  MEDICAL_ONCOLOGY: "Medical Oncology",
  NEPHROLOGY: "Nephrology",
  NEUROLOGY: "Neurology",
  NEUROSURGERY: "Neurosurgery",
  NUCLEAR_MEDICINE: "Nuclear Medicine",
  OBSTETRICS: "Obstetrics",
  OCCUPATIONAL_MEDICINE: "Occupational Medicine",
  ONCOLOGY: "Oncology",
  OPHTHALMOLOGY: "Ophthalmology",
  ORAL_MAXILLOFACIAL_SURGERY: "Oral and Maxillofacial Surgery",
  ORTHOPEDIC_SURGERY: "Orthopedic Surgery",
  OTOLARYNGOLOGY: "Otolaryngology (ENT)",
  PAIN_MEDICINE: "Pain Medicine",
  PALLIATIVE_CARE: "Palliative Care",
  PATHOLOGY: "Pathology",
  PEDIATRICS: "Pediatrics",
  PHYSICAL_MEDICINE_REHAB: "Physical Medicine and Rehabilitation",
  PLASTIC_SURGERY: "Plastic Surgery",
  PSYCHIATRY: "Psychiatry",
  PULMONOLOGY: "Pulmonology",
  RADIATION_ONCOLOGY: "Radiation Oncology",
  RADIOLOGY: "Radiology",
  REPRODUCTIVE_ENDOCRINOLOGY: "Reproductive Endocrinology and Infertility",
  RHEUMATOLOGY: "Rheumatology",
  SLEEP_MEDICINE: "Sleep Medicine",
  SPORTS_MEDICINE: "Sports Medicine",
  SURGICAL_ONCOLOGY: "Surgical Oncology",
  THORACIC_SURGERY: "Thoracic Surgery",
  TRANSFUSION_MEDICINE: "Transfusion Medicine",
  TRANSPLANT_SURGERY: "Transplant Surgery",
  TRAUMA_SURGERY: "Trauma Surgery",
  UROLOGY: "Urology",
  VASCULAR_SURGERY: "Vascular Surgery"
};



export const AccessMedicalHistoryStatus = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
};