export const Gender = {
  MALE: "male",
  FEMALE: "female",
  OTHER: "other",
};

export const Provider = {
  LOCAL: "local",
  GOOGLE: "google",
};

export const MedicineType = {
  PILLS: "Pills",
  CAPSULE: "Capsule",
  INJECTIONS: "Injections",
  LIQUID: "Liquid",
  TABLET: "Tablet",
  SYRUP: "Syrup",
  INHALER: "Inhaler",
  DROPS: "Drops",
};

export const Frequency = {
  DAILY: "Daily",
  WEEKLY: "Weekly",
  MONTHLY: "Monthly",
  AS_NEEDED: "As Needed",
};

export const DayOfWeek = {
  SAT: "Sat",
  SUN: "Sun",
  MON: "Mon",
  TUE: "Tue",
  WED: "Wed",
  THU: "Thu",
  FRI: "Fri",
};

export const IntakeInstruction = {
  AFTER_EAT: "After eat",
  WHILE_EATING: "While eating",
  BEFORE_EAT: "Before eat",
  AT_BEDTIME: "At Bedtime",
  EMPTY_STOMACH: "Empty stomach",
};

export const ReminderStatus = {
  PENDING: 'Pending',
  TAKEN: 'Taken',
  MISSED: 'Missed',
  SKIPPED: 'Skipped',
};

export const Images = {
  PATIENT_FEMALE: "default_patient_female",
  PATIENT_MALE : "default_patient_male",
  OTHER : "default_patient_other",
  DOCTOR_FEMALE : "default_doctor_female",
  DOCTOR_MALE:"default_doctor_male"
}

export const Diseases = [
  "Acne",
  "Acute Flaccid Myelitis (AFM)",
  "Addison’s Disease",
  "Adenovirus Infection",
  "AIDS",
  "Alzheimer’s Disease",
  "Anemia",
  "Ankylosing Spondylitis",
  "Anorexia Nervosa",
  "Anthrax",
  "Arthritis",
  "Asthma",
  "Atherosclerosis",
  "Autism Spectrum Disorder",
  "Bipolar Disorder",
  "Bladder Cancer",
  "Breast Cancer",
  "Bronchitis",
  "Bulimia Nervosa",
  "Cancer",
  "Celiac Disease",
  "Cervical Cancer",
  "Chickenpox",
  "Chlamydia",
  "Cholera",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Cirrhosis",
  "Colorectal Cancer",
  "Congestive Heart Failure",
  "Crohn’s Disease",
  "Cystic Fibrosis",
  "Dengue Fever",
  "Depression",
  "Diabetes",
  "Diverticulitis",
  "Down Syndrome",
  "Ebola Virus Disease",
  "Eczema",
  "Endometriosis",
  "Epilepsy",
  "Epidermolysis Bullosa",
  "Fibromyalgia",
  "Fifth Disease",
  "Food Allergies",
  "Gallstones",
  "Gastritis",
  "Gastroenteritis",
  "Genital Herpes",
  "Genital Warts",
  "Giardiasis",
  "Glaucoma",
  "Gonorrhea",
  "Gout",
  "Graves’ Disease",
  "Haemophilus Influenzae Invasive Disease",
  "Hand, Foot, and Mouth Disease",
  "Hantavirus",
  "Heart Disease",
  "Hemophilia",
  "Hepatitis A",
  "Hepatitis B",
  "Hepatitis C",
  "Herpes",
  "HIV",
  "Huntington’s Disease",
  "Hypertension",
  "Hypothyroidism",
  "Ichthyosis",
  "Influenza",
  "Irritable Bowel Syndrome (IBS)",
  "Juvenile Arthritis",
  "Kawasaki Disease",
  "Kidney Stones",
  "Legionellosis",
  "Leprosy",
  "Leptospirosis",
  "Leukemia",
  "Liver Cancer",
  "Lung Cancer",
  "Lupus",
  "Lyme Disease",
  "Malaria",
  "Marfan Syndrome",
  "Measles",
  "Meningitis",
  "Migraine",
  "Molluscum Contagiosum",
  "Mononucleosis",
  "Mpox",
  "Multiple Sclerosis",
  "Mumps",
  "Muscular Dystrophy",
  "Myasthenia Gravis",
  "Norovirus",
  "Obesity",
  "Obsessive-Compulsive Disorder (OCD)",
  "Osteogenesis Imperfecta",
  "Osteonecrosis",
  "Osteopetrosis",
  "Osteoporosis",
  "Ovarian Cancer",
  "Pancreatic Cancer",
  "Parkinson’s Disease",
  "Peptic Ulcer",
  "Pertussis",
  "Pneumonia",
  "Polio",
  "Post-Traumatic Stress Disorder (PTSD)",
  "Prostate Cancer",
  "Psoriasis",
  "Q Fever",
  "Rabies",
  "Rheumatoid Arthritis",
  "Rubella",
  "Salmonellosis",
  "Scabies",
  "Schizophrenia",
  "Sickle Cell Anemia",
  "Sinusitis",
  "Skin Cancer",
  "Stroke",
  "Syphilis",
  "Tetanus",
  "Thyroid Cancer",
  "Tonsillitis",
  "Tuberculosis",
  "Ulcerative Colitis",
  "Urinary Tract Infection (UTI)",
  "Varicella",
  "Whooping Cough",
  "Yellow Fever",
  "Zika Virus"
];

// Comment to encourage updates
// TODO: Update this list periodically with new diseases identified in 2025 from sources like WHO or CDC.